// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:shoebuddy/firebase_options.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDztP9sShBQPjaYp6xLwoy1OcX3PkTZ3Mo',
    appId: '1:712255201754:web:730222af5f2a20173560e3',
    messagingSenderId: '712255201754',
    projectId: 'shoebuddy-e10ce',
    authDomain: 'shoebuddy-e10ce.firebaseapp.com',
    storageBucket: 'shoebuddy-e10ce.appspot.com',
    measurementId: 'G-G0C7L116F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8I7ZpVJ3_vCdWTN4AtCAQ31zitc3o2U',
    appId: '1:712255201754:android:334b786dc031a40f3560e3',
    messagingSenderId: '712255201754',
    projectId: 'shoebuddy-e10ce',
    storageBucket: 'shoebuddy-e10ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgR0XxvKi4ZSvmJUYbKkJCDERhRbxgQM',
    appId: '1:712255201754:ios:815d7f3de3dc1d013560e3',
    messagingSenderId: '712255201754',
    projectId: 'shoebuddy-e10ce',
    storageBucket: 'shoebuddy-e10ce.appspot.com',
    iosClientId: '712255201754-lpchuqkpnc9mfq35jbcv5bvnriv5vnlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoebuddy',
  );
}
